# Netlify configuration for GameKing website
[build]
  publish = "."

[[redirects]]
  from = "/tictactoe"
  to = "/templates/tictactoe.html"
  status = 200

[[redirects]]
  from = "/beforegta6"
  to = "/templates/beforegta6.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/templates/index.html"
  status = 200
