# Netlify configuration for GameKing website
[build]
  publish = "dist"
  command = "python netlify_build.py"

[[redirects]]
  from = "/tictactoe"
  to = "/tictactoe.html"
  status = 200

[[redirects]]
  from = "/beforegta6"
  to = "/beforegta6.html"
  status = 200

[[redirects]]
  from = "/dashy"
  to = "/dashy.html"
  status = 200
